###############

GPU: [0,1,2,3]

VERBOSE: True

MODEL:
  MODE: 'Dehaze-dilated6-512-overlap'
  SESSION: 'MIRNet'

# Optimization arguments.
OPTIM:
  BATCH_SIZE: 3
  NUM_EPOCHS: 4000
  LR_INITIAL: 2e-4
  #NEPOCH_DECAY: [40]
  #BETA1: 0.9

TRAINING:
  TRAIN_PS: 512
  VAL_PS: 196
  RESUME: True
  TRAIN_DIR: './dataset-512-overlap/' # path to training data
  VAL_DIR: './dataset-512-overlap/'     # path to validation data
  SAVE_DIR: './checkpoints'          # path to save models and images
  SAVE_IMAGES: False
  #VAL_AFTER_EVERY: 1
